name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Swift version
      run: swift --version
    
    - name: Build
      run: swift build
    
    - name: Run tests
      run: swift test